// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRwRZ6cAeMtDdc4A-KSaP5Y-ffPonAH24',
    appId: '1:1086179188580:web:cecbd583b078ca2dd1e471',
    messagingSenderId: '1086179188580',
    projectId: 'vaquinha-99b8b',
    authDomain: 'vaquinha-99b8b.firebaseapp.com',
    databaseURL: 'https://vaquinha-99b8b-default-rtdb.firebaseio.com',
    storageBucket: 'vaquinha-99b8b.appspot.com',
    measurementId: 'G-QJPRKVM1VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNJQHUX802B2Ry8aRJH-1V45hB4nMLtmQ',
    appId: '1:1086179188580:android:fb47d4fc87918bc2d1e471',
    messagingSenderId: '1086179188580',
    projectId: 'vaquinha-99b8b',
    databaseURL: 'https://vaquinha-99b8b-default-rtdb.firebaseio.com',
    storageBucket: 'vaquinha-99b8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcXqhJx0FcZj4ONBs315j4O2tjEw_VNg0',
    appId: '1:1086179188580:ios:a6ee8fe2b3fb5fd5d1e471',
    messagingSenderId: '1086179188580',
    projectId: 'vaquinha-99b8b',
    databaseURL: 'https://vaquinha-99b8b-default-rtdb.firebaseio.com',
    storageBucket: 'vaquinha-99b8b.appspot.com',
    iosClientId: '1086179188580-bdudbvsblrc7mkhbm0v7bdud7bc2u48l.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaquinha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcXqhJx0FcZj4ONBs315j4O2tjEw_VNg0',
    appId: '1:1086179188580:ios:24a9bb5ffafadae0d1e471',
    messagingSenderId: '1086179188580',
    projectId: 'vaquinha-99b8b',
    databaseURL: 'https://vaquinha-99b8b-default-rtdb.firebaseio.com',
    storageBucket: 'vaquinha-99b8b.appspot.com',
    iosClientId: '1086179188580-csktpjailub9g53aeoj3t4b1qq5vipsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaquinha.RunnerTests',
  );
}
